# Generated by Django 4.2.7 on 2023-11-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='')),
                ('template_type', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=100)),
                ('batch_no', models.IntegerField(max_length=100)),
                ('a_r_no', models.IntegerField(max_length=100)),
            ],
        ),
    ]
