# Generated by Django 5.0 on 2024-01-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rineapp', '0005_exceldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='a_r_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='template',
            name='batch_no',
            field=models.IntegerField(),
        ),
    ]
