# Generated by Django 5.0 on 2024-02-07 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rineapp', '0007_rename_template_name_uploadedfile_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldocument',
            old_name='title',
            new_name='field',
        ),
        migrations.RemoveField(
            model_name='exceldocument',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='exceldocument',
            name='uploaded_files',
            field=models.FileField(default=1, upload_to='excels/', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xlsm', 'xltx'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_file',
            field=models.FileField(upload_to='Uploaded files', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xlsm', 'xltx'])]),
        ),
    ]
