# Generated by Django 5.0 on 2024-03-01 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rineapp', '0008_rename_title_exceldocument_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('word_file', models.FileField(upload_to='word_files/')),
            ],
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AlterField(
            model_name='exceldocument',
            name='uploaded_files',
            field=models.FileField(upload_to='Uploaded files', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xlsm', 'xltx'])]),
        ),
    ]
