# Generated by Django 5.0 on 2024-03-05 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rineapp', '0009_worddocument_delete_template_delete_uploadedfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worddocument',
            name='word_file',
        ),
        migrations.AddField(
            model_name='worddocument',
            name='uploaded_files',
            field=models.FileField(default=1, upload_to='word_files/', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx'])]),
            preserve_default=False,
        ),
    ]
