# Generated by Django 5.0 on 2024-01-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_category',
            field=models.CharField(choices=[('analyst', 'Analyst'), ('controller', 'Controller'), ('manager', 'Manager')], max_length=20),
        ),
    ]
